### ISSUE TITLE
Editor is not accessible in osu!

### ISSUE THREAD

**Issue by Hay1tsme** [LumpBloom7/osu-maimai#233]
Fresh install of osu!laser 2021.608.0 and sentakki 2021.608.0 on Windows 10 21H1
Relevant section of log file included below.
```
2021-06-08 23:28:06 [verbose]: Screen changed → Editor
2021-06-08 23:28:06 [error]: An unhandled error has occurred.
2021-06-08 23:28:06 [error]: System.ArgumentException: Only beatmaps in the osu, taiko, catch, or mania rulesets can be encoded to the legacy beatmap format. (Parameter 'beatmap')
2021-06-08 23:28:06 [error]: at osu.Game.Beatmaps.Formats.LegacyBeatmapEncoder..ctor(IBeatmap beatmap, ISkin skin)
2021-06-08 23:28:06 [error]: at osu.Game.Screens.Edit.EditorChangeHandler.UpdateState()
2021-06-08 23:28:06 [error]: at osu.Game.Screens.Edit.TransactionalCommitComponent.SaveState()
2021-06-08 23:28:06 [error]: at osu.Game.Screens.Edit.EditorChangeHandler..ctor(EditorBeatmap editorBeatmap)
2021-06-08 23:28:06 [error]: at osu.Game.Screens.Edit.Editor.load(OsuColour colours, OsuConfigManager config)
2021-06-08 23:28:06 [error]: --- End of stack trace from previous location ---
2021-06-08 23:28:06 [error]: at osu.Framework.Allocation.BackgroundDependencyLoaderAttribute.<>c__DisplayClass6_0.<CreateActivator>b__4(Object target, IReadOnlyDependencyContainer dc)
2021-06-08 23:28:06 [error]: at osu.Framework.Allocation.DependencyActivator.activate(Object obj, IReadOnlyDependencyContainer dependencies)
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Drawable.load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies)
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Drawable.Load(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Drawable.LoadFromAsync(IFrameBasedClock clock, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext)
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.loadComponents[TLoadable](List`1 components, IReadOnlyDependencyContainer dependencies, Boolean isDirectAsyncContext, CancellationToken cancellation)
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass17_0`1.<LoadComponentsAsync>b__1()
2021-06-08 23:28:06 [error]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2021-06-08 23:28:06 [error]: --- End of stack trace from previous location ---
2021-06-08 23:28:06 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2021-06-08 23:28:06 [error]: --- End of stack trace from previous location ---
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.<>c__DisplayClass17_2`1.<LoadComponentsAsync>b__4()
2021-06-08 23:28:06 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2021-06-08 23:28:06 [error]: at osu.Framework.Threading.Scheduler.Update()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-06-08 23:28:06 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2021-06-08 23:28:06 [error]: at osu.Framework.Threading.GameThread.ProcessFrame()
2021-06-08 23:28:06 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
```

**Comment by LumpBloom7** [comment]
osu!lazer currently doesn't support custom ruleset editors. The osu-side issue is tracked at https://github.com/ppy/osu/issues/12612.

**Comment by Kuina-chan** [comment]
Resolved in the newest release of sentakki
